workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up iOS Code Signing
        script: |
          # If you use automatic code signing, you need to configure App Store Connect API keys in Codemagic UI.
          echo "Run Code Signing"
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS App
        script: |
          flutter build ipa --release \
            --dart-define=ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
